# Generated by Django 2.1 on 2019-07-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(db_column='music_id', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='music_name', max_length=255)),
                ('singer', models.CharField(db_column='singer', max_length=255)),
                ('came_from', models.CharField(blank=True, db_column='came_from', max_length=255)),
                ('kbps', models.CharField(blank=True, db_column='music_kbps', max_length=255)),
                ('size', models.CharField(blank=True, db_column='music_size', max_length=255)),
                ('language', models.CharField(blank=True, db_column='music_language', max_length=255)),
                ('released_data', models.CharField(blank=True, db_column='released_data', max_length=255)),
                ('url', models.CharField(db_column='bdyun_url', max_length=255)),
                ('password', models.CharField(blank=True, db_column='bdyun_password', max_length=255)),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'music_info',
            },
        ),
    ]
